version: "3.9"

services:

  backend:
    build: ./backend

    ports:
      - "8001:8001"

    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend

    ports:
      - "5174:5174"

    volumes:
      - ./frontend:/app

    depends_on:
      - backend